
write_report_template <- function(rmd_file, title = "MCD / CellMCD Analysis Report") {
  txt <- c(
    '---',
    paste0('title: "', title, '"'),
    'output:',
    '  html_document:',
    '    toc: true',
    '    toc_depth: 3',
    '    number_sections: true',
    '    theme: readable',
    '---',
    '',
    '```{r setup, include=FALSE}',
    'knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)',
    'library(data.table)',
    'library(ggplot2)',
    '',
    'gout <- readRDS(file.path("report_data", "gout.rds"))',
    'tout <- readRDS(file.path("report_data", "tout.rds"))',
    'params <- readRDS(file.path("report_data", "params.rds"))',
    '',
    'gout <- as.data.table(gout)',
    'tout <- as.data.table(tout)',
    '',
    'has_col <- function(dt, x) x %in% names(dt)',
    'fmt_num <- function(x, digits = 3) {',
    '  ifelse(is.na(x), NA, round(x, digits))',
    '}',
    '```',
    '',
    '# Overview',
    '',
    'This report summarizes the minumum covariant determinant (MCD) and cell-wise MCD (cellMCD) analysis results for CRIPSR drug screens with multiple experiments. It is intended to help yous interpret the generated PDFs and Excel tables.',
    '',
    'The main goal of this analysis is to help identify genes with structured multivariate behavior across contrasts or samples.',
    '',
    '```{r overview-table}',
    'overview <- data.table(',
    '  Metric = c(',
    '    "Number of groups",',
    '    "Number of significant/non-none genes"',
    '  ),',
    '  Value = c(',
    '    uniqueN(gout$group_id),',
    '    if (has_col(gout, "pattern")) uniqueN(gout[pattern != "none", gene]) else NA_integer_',
    '  )',
    ')',
    'knitr::kable(overview)',
    '```',
    '',
    '# Output files',
    '',
    'The analysis usually produces the following files (not an exhaustive list):',
    '',
    '- `class_results.pdf`: plotting results for genes grouped by predefined gene class.',
    '- `clustering_results.pdf`: plotting results for genes grouped by hierarchical clustering.',
    '- `pair_plots.pdf`: Scatter plots showing pairwise comparisons of samples.',
    '- `significant_gene_table.xlsx`: gene-level summary table of significant genes only.',
    '- `tout_zres_table.xlsx`: contrast-level or sample-level table of significant genes only.',
    '- `analysis_report.html`: this guided interpretation report.',
    '',
    '# How to interpret key columns',
    '',
    '## Gene class',
    '',
    '`gene_class` summarizes the dominant behavior of a gene.',
    '',
    '| Gene class | Interpretation |',
    '|---|---|',
    '| Global Positive | Gene tends to show positive signal across many contrasts/samples. |',
    '| Global Negative | Gene tends to show negative signal across many contrasts/samples. |',
    '| Global Mixed | Gene shows strong signal but direction varies across contrasts/samples. |',
    '| Local Positive | Gene shows positive signal in a subset of contrasts/samples. |',
    '| Local Negative | Gene shows negative signal in a subset of contrasts/samples. |',
    '| None | Gene was not classified as showing a structured signal. |',
    '',
    '## Mahalanobis distance',
    '',
    'The Mahalanobis distance measures how far a gene is from the robust multivariate center. Larger values indicate stronger multivariate outlier behavior. This is the main gene-level effect size that summarizes a genes behavior across all samples. Thhis has an accompanying p-value',
    '',
    '## ssZ',
    '',
    '`ssZ` stands for sum of squares Z-residual. Simular to the mahalanibis distance, it summarizes the strength of a gene\'s signal across all its contrasts or samples. Larger values indicate stronger aggregate signal.',
    '',
    '## Zres',
    '',
    '`Zres` is the Z-residual standardized signal at the contrast/sample level. It is the main effect size produced from cellwise MCD. It helps show which specific samples drive a gene-level result. This does not have an associated p-value',
    '',
    '## W',
    '',
    '`W` is a weight or cellwise diagnostic value produced from cellwise MCD and takes a value 0 or 1 to flag which individual samples are outlying. It can help identify which individual samples contribute most strongly to a gene\'s detected pattern.',
    '',
    '## eff_n',
    '',
    '`eff_n` is the effective number of contrasts/samples contributing to the gene-level signal.',
    '',
    'It is computed as:',
    '',
    '```text',
    'eff_n = ssZ / max_abs_Z^2',
    '```',
    '',
    'where:',
    '',
    '- `ssZ` is the total squared residual signal across contrasts/samples.',
    '- `max_abs_Z^2` is the squared largest absolute `Zres` value.',
    '',
    'Interpretation:',
    '',
    '| eff_n value | Interpretation |',
    '|---|---|',
    '| Near 1 | Most of the signal is driven by one contrast/sample. |',
    '| Larger values | Signal is spread across multiple contrasts/samples. |',
    '| Near n_total_samples (total # of samples)| Signal is broadly distributed across available observations. |',
    '',
    'For example, if a gene has one very large `Zres` value and all others are small, `eff_n` will be close to 1. If several contrasts/samples contribute similarly, `eff_n` will increase.',
    '',
    '`eff_n` is used to compute `p_global`, so it directly contributes to whether a gene is classified as local or global.',
    '',
    '## p_global',
    '',
    '`p_global` estimates whether a gene-level signal is distributed broadly across contrasts/samples or concentrated in only a small subset.',
    '',
    'It is computed from the effective number of contributing observations:',
    '',
    '```text',
    'p_global = (eff_n - 1) / max(1, n_total_samples - 1)',
    '```',
    '',
    'Interpretation:',
    '',
    '| p_global value | Interpretation |',
    '|---|---|',
    '| Near 0 | Signal is local; one or a few contrasts/samples dominate. |',
    '| Near 0.5 | Signal is intermediate or partially distributed. |',
    '| Near 1 | Signal is global; many contrasts/samples contribute. |',
    '',
    'In this workflow, genes with `p_global >= 0.5` are classified as `global`, while genes below this threshold are classified as `local`, provided they are not `none`.',
    '',
    'Important caution: `p_global` should be interpreted together with `ssZ`, `Zres`, and the heatmaps. A high `p_global` describes how broadly the signal is distributed, not necessarily how biologically important the gene is.',
    '',
    '# Recommended interpretation workflow',
    '',
    'Use this order when reviewing results:',
    '',
    '1. Start with the class or cluster summary bar plots and t-SNE plots, which tell you the overarching patterns in your data',
    '2. Here, you can identify groups with many non-none or significant genes.',
    '3. Review the centroid heatmaps (which describe the median Zresidual values in each class or cluster) to understand the average pattern of each class or cluster.',
    '4. Review gene heatmaps to inspect top genes within important classes or clusters.',
    '5. Use the significant gene table to rank genes by Mahalanobis distance, `ssZ`, or adjusted p-value if available.',
    '6. Use the Zres table to determine which contrasts, treatments, cell lines, or timepoints drive each gene result.',
    '',
    '# Gene class summary',
    '',
    '```{r class-summary}',
    'if (has_col(gout, "gene_class")) {',
    '  class_summary <- unique(gout[, .(group_id, gene, gene_class)])[',
    '    !is.na(gene_class),',
    '    .N,',
    '    by = .(group_id, gene_class)',
    '  ]',
    '  class_summary[, prop := N / sum(N), by = group_id]',
    '  class_summary[, prop := round(100 * prop, 1)]',
    '  setorder(class_summary, group_id, -N)',
    '  knitr::kable(class_summary, col.names = c("Group", "Gene class", "N genes", "Percent"))',
    '} else {',
    '  cat("No gene_class column was found.")',
    '}',
    '```',
    '',
    '# Cluster summary',
    '',
    '```{r cluster-summary}',
    'cluster_col <- NULL',
    'if (has_col(gout, "embedding_cluster")) cluster_col <- "embedding_cluster"',
    'if (is.null(cluster_col) && has_col(gout, "cluster")) cluster_col <- "cluster"',
    '',
    'if (!is.null(cluster_col)) {',
    '  cluster_summary <- unique(gout[, .(group_id, gene, cluster = get(cluster_col))])[',
    '    !is.na(cluster),',
    '    .N,',
    '    by = .(group_id, cluster)',
    '  ]',
    '  cluster_summary[, prop := N / sum(N), by = group_id]',
    '  cluster_summary[, prop := round(100 * prop, 1)]',
    '  setorder(cluster_summary, group_id, cluster)',
    '  knitr::kable(cluster_summary, col.names = c("Group", "Cluster", "N genes", "Percent"))',
    '} else {',
    '  cat("No cluster column was found.")',
    '}',
    '```',
    '',
    '# Top genes by group',
    '',
    'The table below lists top genes by Mahalanobis distance when available. These are often good starting points for biological review.',
    '',
    '```{r top-genes}',
    'if (has_col(gout, "mahalanobis")) {',
    '  cols <- intersect(c(',
    '    "group_id", "gene", "gene_class", "embedding_cluster",',
    '    "pattern", "mahalanobis", "ssZ", "p_global", "eff_n"',
    '  ), names(gout))',
    '',
    '  top_genes <- unique(gout[, ..cols])',
    '  top_genes <- top_genes[order(group_id, -mahalanobis)]',
    '  top_genes <- top_genes[, head(.SD, 10), by = group_id]',
    '',
    '  numeric_cols <- intersect(c("mahalanobis", "ssZ", "p_global", "eff_n"), names(top_genes))',
    '  for (cc in numeric_cols) top_genes[, (cc) := fmt_num(get(cc), 3)]',
    '',
    '  knitr::kable(top_genes)',
    '} else {',
    '  cat("No mahalanobis column was found.")',
    '}',
    '```',
    '',
    '# How to read `class_results.pdf`',
    '',
    'This PDF groups genes by `gene_class`.',
    '',
    'Use it to answer:',
    '',
    '- Which predefined behavior classes are most common?',
    '- Which classes dominate each experimental group?',
    '- Do centroid heatmaps show coherent class-level patterns?',
    '- Which individual genes drive each class?',
    '',
    'Important pages to inspect:',
    '',
    '1. Class proportion bar plots.',
    '2. t-SNE plots colored by gene class.',
    '3. Class centroid heatmaps.',
    '4. Gene-level heatmaps within each class.',
    '5. Zres-by-gene-index plots.',
    '',
    '# How to read `clustering_results.pdf`',
    '',
    'This PDF groups genes by computed clusters.',
    '',
    'Use it to answer:',
    '',
    '- Are there data-driven gene groups that share similar multivariate patterns?',
    '- Do clusters correspond to known biological classes?',
    '- Are some clusters enriched for local or global behavior?',
    '- Which genes best represent each cluster?',
    '',
    'Clusters are descriptive groups. They should be interpreted using the centroid heatmaps, gene heatmaps, and gene annotation tables.',
    '',
    '# How to read `pair_plots.pdf`',
    '',
    'The pair plots show relationships between contrasts. They are useful for diagnosing whether signals are shared across contrasts or driven by contrast-specific behavior.',
    '',
    'Genes highlighted in these plots are typically high-ranking or flagged genes. Quadrant counts help summarize whether genes tend to move in the same or opposite directions across pairs of contrasts.',
    '',
    '# How to use the Excel tables',
    '',
    '## Significant gene table',
    '',
    'Use this table for gene-level prioritization.',
    '',
    'Recommended sorting order:',
    '',
    '1. `group_id`',
    '2. `gene_class` or `embedding_cluster`',
    '3. descending `mahalanobis`',
    '4. descending `ssZ`',
    '',
    'Contrast matrix columns, when present, can be used to determine whether a gene has positive, negative, mixed, or local behavior.',
    '',
    '## Zres table',
    '',
    'Use this table to understand which specific contrasts, treatments, cell lines, or timepoints drive each gene-level result.',
    '',
    'Useful columns include:',
    '',
    '- `gene`',
    '- `contrast`',
    '- `treatment`',
    '- `cell_line`',
    '- `timepoint`',
    '- `Zres`',
    '- `W`',
    '- `gene_class`',
    '- `embedding_cluster`',
    '- `mahalanobis`',
    '',
    '# Important cautions',
    '',
    'These outputs are intended to prioritize genes and patterns for follow-up. They should not be interpreted as final biological proof by themselves.',
    '',
    'yous should avoid over-interpreting:',
    '',
    '- very small clusters,',
    '- genes with high signal driven by only one contrast unless local behavior is expected,',
    '- classes with very few genes,',
    '- patterns that are inconsistent with experimental design or batch structure.',
    '',
    '# Parameters used',
    '',
    '```{r params}',
    'if (length(params) > 0) {',
    '  param_dt <- data.table(',
    '    Parameter = names(params),',
    '    Value = vapply(params, function(x) paste(x, collapse = ", "), character(1))',
    '  )',
    '  knitr::kable(param_dt)',
    '} else {',
    '  cat("No parameter list was supplied.")',
    '}',
    '```',
    '',
    '# Suggested next steps',
    '',
    'After reviewing this report, yous should:',
    '',
    '1. Select top genes within important classes or clusters.',
    '2. Confirm that the Zres pattern matches the expected experimental design.',
    '3. Compare top genes against known biology or pathway annotations.',
    '4. Use the Excel tables for downstream enrichment or validation analyses.',
    '5. Treat clusters as hypotheses that require biological interpretation.',
    ''
  )
  
  writeLines(txt, con = rmd_file)
}

make_analysis_report <- function(
    gout,
    tout,
    out_dir,
    report_file = "analysis_report.html",
    params = list(),
    title = "CRISPR Screen MCD / CellMCD Analysis Report",
    quiet = TRUE
) {
  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required to generate the analysis report.", call. = FALSE)
  }

  if (!requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required to generate the analysis report.", call. = FALSE)
  }

  if (!dir.exists(out_dir)) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }

  gout <- data.table::as.data.table(data.table::copy(gout))
  tout <- data.table::as.data.table(data.table::copy(tout))

  rds_dir <- file.path(out_dir, "report_data")
  dir.create(rds_dir, recursive = TRUE, showWarnings = FALSE)

  saveRDS(gout, file.path(rds_dir, "gout.rds"))
  saveRDS(tout, file.path(rds_dir, "tout.rds"))
  saveRDS(params, file.path(rds_dir, "params.rds"))

  rmd_file <- file.path(out_dir, "analysis_report.Rmd")

  write_report_template(
    rmd_file = rmd_file,
    title = title
  )

  out <- rmarkdown::render(
    input = rmd_file,
    output_file = report_file,
    output_dir = out_dir,
    quiet = quiet
  )

  invisible(out)
}